Repository w3c/pointerevents, pull requests merged in 2021-06, with the labels that each got.

#382 Expand the definition/explanation of predicted events timestamps
  index.html
Labels: editorial, v3

#383 Explicit note about pointerrawmove having an empty predicted event list
  index.html
Labels: v3

#381 Refreshing references using latest respec magic
  index.html
Labels: editorial

#386 task queue is not reliable HTML concept. Use event loop instead
  index.html
Labels: v3

#389 More minor tweaks
  index.html
Labels: editorial
